### ISSUE TITLE
OperationalWithSyncPending stuck - Minor Update Wave 2 2020 BC

### ISSUE THREAD

**Issue by itconsultingnc** [MicrosoftDocs/dynamics365smb-devitpro-pb#1768] opened 2021-03-20 11:08 UTC
Hi , 

At the end of upgrading path for Minor Upgrade, there is the final step :

Update application version

But , if we end at the point , we get stuck we OperationalWithSyncPending  status.
So it is missing the next command :

Start-NavDataUpgrade  -ServerInstance BCinstance -FunctionExecutionMode Serial

I got stuck few day , doing again and again the process.
Adding this command line validated the upgrade.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a0ff77-d5c2-3df3-f7fa-cf5914b69f1d
* Version Independent ID: 7f11e180-b1d1-54d5-4e53-21165472ceaf
* Content: [Install a version 17 update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v17)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment] 2021-11-23 09:30
Hello,

Thanks for the feedback. This seems odd, especially because the tenant should have synced in this [step](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v17#synchronize-tenant).

Unlike the Set-NAVApplication cmdlet for changing the application version version, which requires a database sync and upgrade, using the Set-NAVServerConfiguration - SolutionVersionExtension  cmdlet doesn't change the database. I haven't been able to reproduce this error. Have you experienced the same issue in later updates?

**Comment by jswymer** [comment] 2023-01-16 13:31
Hello,

We couldn't reproduce this on version 17 or for the minor updates on latest supported releases v18-21. We will close this issue for the documentation. If you're still experiencing the problem, we recommend contacting support. Thanks!

**Closed by jswymer** 2023-01-16 13:31 UTC
Labels: upgrade
