### ISSUE TITLE
ODATA API set empty value to GUID field using PHP

### ISSUE THREAD

**Issue by aleksandr-simplyhq** [MicrosoftDocs/dynamics365smb-devitpro-pb#2154] opened 2021-12-16 10:50 UTC
Hello, I created a thread in the forum but did not get a answer. Can you check it?
https://community.dynamics.com/business/f/dynamics-365-business-central-forum/441795/odata-api-set-empty-value-to-guid-field/1214969
Maybe you can help me? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7021c38-6363-34f2-1673-13437d884fb3
* Version Independent ID: 81107f66-ac2f-5763-941b-b521151253f4
* Content: [Update items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_item_update)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_item_update.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_item_update.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2021-12-16 14:30
Hello, the data type of the itemCategoryId is a GUID. And from the example in docs, the format can be, for example: "itemCategoryId": "e21a6a90-44e3-ea11-bb43-000d3a2feca1" - if you want to insert an empty value, I believe that you can enter "itemCategoryId": "00000000-0000-0000-0000-000000000000". Can you check if that works?
For more information, please see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/guid/guid-data-type

**Comment by aleksandr-simplyhq** [comment] 2021-12-17 06:02
Yes, I tried that in the first place. It's written in the thread header (I edited the header message to specify the correct zeros identifier).

The query returns me an error
`The Item Category does not exist. Identification fields and values: {00000000-0000-0000-0000-000000000000}`

**Comment by dnpb** [comment] 2021-12-17 09:07
It seems the code in the Item table is wrong:
![image](https://user-images.githubusercontent.com/63455896/146518771-2c4dff80-5b58-40cc-9e09-8320d6a0cbc5.png)
Surely if the Id is null, it should **not** try to get it...?

**Comment by nikolakukrika** [comment] 2021-12-17 09:42
It is a bug, we will get it fixed. Thanks for reporting it.

**Comment by dnpb** [comment] 2021-12-17 09:43
Thanks a tonne! I believe Jesper at MS already noticed it, definitely independently from me posting it on Yammer ;-)

**Comment by JesperSchulz** [comment] 2021-12-17 09:46
And I forwarded it into the hands of the most capable developer I could find and he jumped on it instantly and reports back on all channels. That's how we do things around here 🥂 🥳

**Comment by dnpb** [comment] 2021-12-17 09:47
Of course, the other side of the issue is that the Item Category Code won't have been getting populated from the Item Category Id, since the if condition was the wrong way around. Will there be a data upgrade fix for that? What am I saying - of course there will ;-)

**Comment by dnpb** [comment] 2021-12-17 10:31
from Yammer:
> Nikola Kukrika – 40 minutes ago
> It is a bug that we will HF. The few environments could be affected if they were using this functionality.
> We can give you a PTE to fix the data and will create an action that you can invoke to repair the data. We can also see to introduce the upgrade for the next minor in SaaS, but this depends if we have keys on these fields (so we don't encounter performance issues and long running upgrades)

**Comment by SusanneWindfeldPedersen** [comment] 2021-12-17 12:47
Thanks for the great collaboration. We will close this issue and await the HF.

**Closed by SusanneWindfeldPedersen** 2021-12-17 12:47 UTC
