### ISSUE TITLE
Need Links

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1555] opened 2020-11-23 16:38 UTC
Hello,

You have this great list of available page types, but none of them are linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0363ee62-5ad8-5e9a-82f5-27b3fa351506
* Version Independent ID: cb7dcfb3-3766-35a9-dade-dc5d450f6e25
* Content: [Pages Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview)
* Content Source: [dev-itpro/developer/devenv-pages-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-pages-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2020-11-24 08:34
Closing this as a duplicate of #1554

**Closed by SusanneWindfeldPedersen** 2020-11-24 08:34 UTC
