### ISSUE TITLE
Error regarding version when syncronizing the Base Application

### ISSUE THREAD

**Issue by Lethager** [MicrosoftDocs/dynamics365smb-devitpro-pb#1835] opened 2021-05-06 08:11 UTC
Hello

When I try to Syncronize the Base Application I get this error:

![image](https://user-images.githubusercontent.com/39183085/117264286-6120f300-ae53-11eb-84f2-fea3f39eb42d.png)
[](url)

PS C:\Windows\system32> Sync-NAVApp -ServerInstance $ins -Tenant $Tenant -Name "Base Application" -Version $Base_Version
Sync-NAVApp : Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for System Application by Microsof
t 18.0.0.0.
At line:1 char:1
+ Sync-NAVApp -ServerInstance $ins -Tenant $Tenant -Name "Base Applicat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC180/Default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.SyncNavApp
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05a03500-5e14-08ad-8fe0-f1bd752312b9
* Version Independent ID: 543729ab-ec13-3e2a-dc1d-73a9567b9802
* Content: [Upgrading Unmodified C/AL Application to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v18)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v14-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-v14-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by Lethager** [comment] 2021-05-06 09:38
Hello 

I had missed to Sync the System Application first.

But now I get another error:
![image](https://user-images.githubusercontent.com/39183085/117276798-89aeea00-ae5f-11eb-9837-f62d44280353.png)

**Comment by jswymer** [comment] 2021-05-06 10:17
Hello, thanks for the feedback.

From what I can tell, these two fields where added in 18.0. Can you tell me the version of 14 that you're upgrading from?

**Comment by Lethager** [comment] 2021-05-06 10:21
Hello

I am upgrading from  14.0.46884

Med venlig hilsen
Henry Lethager
Konsulent |H: + 45 78 79 40 40 | D: +45 78 79 41 54 | ***@***.***

***@***.***D74272.5DC62290]<https://www.erpgruppen.dk/>

 ***@***.***D74272.5DC62290] <https://www.erpgruppen.dk/>  ***@***.***D74272.5DC62290] <https://erpsupporten.dk/>  ***@***.***D74272.5DC62290] <https://www.linkedin.com/company/erpgruppen-a-s/>  ***@***.***D74272.5DC62290] <https://www.facebook.com/ERPgruppen>   IT-løsninger, support og træning til Dynamics 365 Sales, Business Central, NAV og C5

***@***.***D74272.5DC62290]<https://t.xink.io/Tracking/Index/1RwCAPCrAQAi_bEA0>


Fra: jswymer ***@***.***>
Sendt: 6. maj 2021 12:18
Til: MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.***>
Cc: Henry Lethager ***@***.***>; Author ***@***.***>
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Error regarding version when syncronizing the Base Application (#1835)


Hello, thanks for the feedback.

From what I can tell, these two fields where added in 18.0. Can you tell me the version of 14 that you're upgrading from?

**Comment by Lethager** [comment] 2021-05-07 07:48
Hello

Can you help me how to solve this issue??

Med venlig hilsen
Henry Lethager
Konsulent |H: + 45 78 79 40 40 | D: +45 78 79 41 54 | ***@***.***

***@***.***D74326.161349A0]<https://www.erpgruppen.dk/>

 ***@***.***D74326.161349A0] <https://www.erpgruppen.dk/>  ***@***.***D74326.161349A0] <https://erpsupporten.dk/>  ***@***.***D74326.161349A0] <https://www.linkedin.com/company/erpgruppen-a-s/>  ***@***.***D74326.161349A0] <https://www.facebook.com/ERPgruppen>   IT-løsninger, support og træning til Dynamics 365 Sales, Business Central, NAV og C5

***@***.***D74326.161349A0]<https://t.xink.io/Tracking/Index/1RwCAPCrAQAi_bEA0>


Fra: Henry Lethager
Sendt: 6. maj 2021 12:22
Til: MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.***>; MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.***>
Cc: Author ***@***.***>
Emne: SV: [MicrosoftDocs/dynamics365smb-devitpro-pb] Error regarding version when syncronizing the Base Application (#1835)

Hello

I am upgrading from  14.0.46884

Med venlig hilsen
Henry Lethager
Konsulent |H: + 45 78 79 40 40 | D: +45 78 79 41 54 | ***@***.******@***.***>

***@***.***D74326.161349A0]<https://www.erpgruppen.dk/>

 ***@***.***D74326.161349A0] <https://www.erpgruppen.dk/>  ***@***.***D74326.161349A0] <https://erpsupporten.dk/>  ***@***.***D74326.161349A0] <https://www.linkedin.com/company/erpgruppen-a-s/>  ***@***.***D74326.161349A0] <https://www.facebook.com/ERPgruppen>   IT-løsninger, support og træning til Dynamics 365 Sales, Business Central, NAV og C5

***@***.***D74326.161349A0]<https://t.xink.io/Tracking/Index/1RwCAPCrAQAi_bEA0>


Fra: jswymer ***@***.******@***.***>>
Sendt: 6. maj 2021 12:18
Til: MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.******@***.***>>
Cc: Henry Lethager ***@***.******@***.***>>; Author ***@***.******@***.***>>
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Error regarding version when syncronizing the Base Application (#1835)


Hello, thanks for the feedback.

From what I can tell, these two fields where added in 18.0. Can you tell me the version of 14 that you're upgrading from?

**Comment by jswymer** [comment] 2021-05-07 11:03
Hello,

Sorry for the delay. Based on the 14 version, which looks like CU 23, it's not compatible with 18.0. The issue is that the fields in question are not available in 18 until 18.1.

You can see a compatibility matrix [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility#version-14-compatibility). In the upgrade article that you are working with,this is addressed under the **Prerequisites**.

To fix this, you have two options: 1, Wait until 18.1 is released, or 2. Use an earlier 14 version to start, like CU22. Not sure how feasible the second option is for your scenario.

I hope this helps!

**Comment by Lethager** [comment] 2021-05-07 11:06
Hello

When will 18.1 be released?

Med venlig hilsen
Henry Lethager
Konsulent |H: + 45 78 79 40 40 | D: +45 78 79 41 54 | ***@***.***

***@***.***D74341.BC55BDF0]<https://www.erpgruppen.dk/>

 ***@***.***D74341.BC55BDF0] <https://www.erpgruppen.dk/>  ***@***.***D74341.BC55BDF0] <https://erpsupporten.dk/>  ***@***.***D74341.BC55BDF0] <https://www.linkedin.com/company/erpgruppen-a-s/>  ***@***.***D74341.BC55BDF0] <https://www.facebook.com/ERPgruppen>   IT-løsninger, support og træning til Dynamics 365 Sales, Business Central, NAV og C5

***@***.***D74341.BC55BDF0]<https://t.xink.io/Tracking/Index/1RwCAPCrAQAi_bEA0>


Fra: jswymer ***@***.***>
Sendt: 7. maj 2021 13:04
Til: MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.***>
Cc: Henry Lethager ***@***.***>; Author ***@***.***>
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Error regarding version when syncronizing the Base Application (#1835)


Hello,

Sorry for the delay. Based on the 14 version, which looks like CU 23, it's not compatible with 18.0. The issue is that the fields in question are not available in 18 until 18.1.

You can see a compatibility matrix here<https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility#version-14-compatibility>. In the upgrade article that you are working with, this is addressed under the Prerequisites.

To fix this, you have two options: 1, Wait until 18.1 is released, or 2. Use an earlier 14 version to start, like CU22. Not sure how feasible the second option is for your scenario.

I hope this helps!

**Comment by jswymer** [comment] 2021-05-07 11:12
The 18.1 is currently targeted for release in early May, Unfortunately, I do not have an exact date. The release cycle is handled and announced by another team.

**Comment by jswymer** [comment] 2021-05-11 06:27
Hello, I hope this has helped answer your questions. We'll close this issue for now, but if you have more feedback, we'll be happy to reopen it. Thanks!

**Closed by jswymer** 2021-05-11 06:27 UTC
