### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#290] opened 2018-12-20 07:39 UTC
There's a line break error round IdRanges and showMyCode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment] 2018-12-21 07:48
Hello, the line breaks are caused by the way the our help publisher wraps text  (in this case inline code) in table cells. I know it looks wrong but if you copy and paste the code, it does not seem to include the line breaks. I hope this answers your question. Thanks for the feedback!

**Comment by jswymer** [comment] 2018-12-21 10:45
Sorry, I misunderstood. The article has been fixed so that showMyCode will be in its own row. The update will be published soon. Thanks again!

**Closed** 2018-12-21 10:46 UTC
