### ISSUE TITLE
How to insert a Tab character?

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1941] opened 2021-06-28 15:35 UTC
StrSubstNo does not honor the backslash \ character. The work-around is to define a NewLine as follows:

Procedure AddNewLines()
Var
Cr, Lf, TabChar: Char;
NewLine, Tab, TextValue: Text;
Begin
Cr := 13;
Lf := 10;
NewLine := Format(Cr) + Format(Lf);
TabChar := 7;
Tab := Format(TabChar);
TextValue := StrSubstNo('%1: %2 %5%3: %4', Val1, Val2, Val3, Val4, NewLine);
Message(%1, TextValue);
End

1. Perhaps a note could be added mentioning that StrSubstNo does not honor the backslash \
2. Perhaps a simple code example such as the above could be included in the topic

However, I am not aware of any work-around for the Tab character. If I try the above with Tab: Char & Tab := 7 it displays as a non displayable square. If a work-around exists, it would be great if a code example of how to do it was included in this topic.

Procedure AddTab()
Var
TabChar: Char;
Tab, TextValue: Text;
Begin
TabChar := 7;
Tab := Format(TabChar);
TextValue := StrSubstNo('%1: %3: %2', Val1, Val2, Tab);
Message(%1, TextValue);
End
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1080cf85-7b26-ccd8-e2b5-2ccc05a3e40f
* Version Independent ID: 15c2cfa7-6214-3e3f-9ab9-8dd752f242e5
* Content: [Text.StrSubstNo Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-strsubstno-method)
* Content Source: [dev-itpro/developer/methods-auto/text/text-strsubstno-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/text/text-strsubstno-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2021-07-01 13:28
Hi, thanks for the feedback. I believe you can set TabChar := 9; (ascii char for tab) to get a tab. Can you get that to work?

**Comment by j2associates** [comment] 2021-07-01 15:32
Hello Susanne,

Thanks for reaching out to me. I had a total brain cramp on the tab being
Chr(9), not Chr(7). However, the StrSubstNo statement appears to coalesce
all whitespace into a single space with the exception of a new line. Below
is a little test procedure I wrote that demonstrates the issue. I don't
know if this is by design or a long standing bug. I used to do quite a bit
of c# and would sometimes use Chr(160) when I couldn't use a space. As you
can see in the screenshot, that is not coalesced, presumably because it is
not treated as whitespace by the compiler.

It would be nice if there was an optional boolean CoalesceWhitespace
argument included with the StrSubstNo command. It could default to true so
as not to be a breaking change.
[image: image.png]

    local procedure TestStrSubstNoWithWhiespace()
    var
        TabChar, Cr, Lf, BlankChar : Char;
        Tab, NewLine, Spaces5, Blank, Blanks5 : Text;
        Text1, Text2, Text3, Text4, Text5 : Text;
    begin
        Cr := 13;
        Lf := 10;
        NewLine := Format(Cr) + Format(Lf);

        TabChar := 9;
        Tab := Format(TabChar);

        Spaces5 := '     ';

        BlankChar := 160;
        Blank := Format(BlankChar);

        Blanks5 := Blank + Blank + Blank + Blank + Blank;

        Text1 := StrSubstNo('Gary%1%1%1Winey', TabChar);
        Text2 := StrSubstNo('Leslie%1%1%1Winey', Tab);
        Text3 := StrSubstNo('Andrew%1Winey', NewLine);
        Text4 := StrSubstNo('Mark%1Winey', Spaces5);
        Text5 := StrSubstNo('Carrie%1Lozmak', Blanks5);
        if Confirm('%1\%2\%3\%4\%5', true, Text1, Text2, Text3, Text4,
Text5) then;
    end;

Thanks

**Comment by SusanneWindfeldPedersen** [comment] 2021-07-02 09:24
Hi again, I have talked to one of our developers and the behavior of StrSubstNo is similar to what it was in C/AL - we seem to trim all extra spaces and it is by design. An implementation of a tab, would require a definition of what tab is - how many characters - and it is currently not on our backlog to support that. Instead, I can encourage you to submit an [Idea](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest this as a product feature. Thanks again for your feedback, it's much appreciated.

**Comment by SusanneWindfeldPedersen** [comment] 2021-07-09 08:02
Closing this issue.

**Closed by SusanneWindfeldPedersen** 2021-07-09 08:02 UTC
