### ISSUE TITLE
vsix autocomplete doesn't match requirements

### ISSUE THREAD

**Issue by lthomsen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2626] opened 2022-11-22 08:47 UTC
CodeCop AA0241 says "label" should be with lowercase "l", but the VSCode autocomplete says "Label". The VSCode extension and documentation should match.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07ad8bd3-2712-42b5-4647-c26d90852435
* Version Independent ID: fc42bbd3-e20d-400f-926e-b48b83d0717e
* Content: [CodeCop Hidden AA0241 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0241)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0241.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/analyzers/codecop-aa0241.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2022-11-24 15:17
Thanks for the feedback. This is a code defect and not a doc defect. Label should be lowercase, and the docs reflect the code cop analyzer rule. We will open a bug for this and the team will triage it. Thanks again.

**Comment by SusanneWindfeldPedersen** [comment] 2022-12-29 12:58
Thanks for catching this. This is a product bug, and an issue has been created to fix the auto-complete. Closing this issue.

**Comment by SusanneWindfeldPedersen** [comment] 2022-12-30 08:21
Reopening, and providing more insight - this described behavior is by design. For data types in variable and parameter declarations, we are using pascal case instead of lowercase. We'll update the article to reflect that with the next doc refresh. Thanks.

**Closed by SusanneWindfeldPedersen** 2022-12-30 08:21 UTC
Labels: product
