### ISSUE TITLE
Upgrade Error :  BC14 CU5 to BC15 Wave2 (Cronus Database)

### ISSUE THREAD

**Issue by ManishNAV365** [MicrosoftDocs/dynamics365smb-devitpro-pb#774] opened 2019-10-15 10:30 UTC
Hi,

I was upgrading Cronus database Single Tenant from BC14 CU5 (14.0.36457.0) to BC15(15.0.36510.0) Denmark Localization. As per the document at Task 6 Step 4 while synching the Base Application App , it displays the below error for Unsupported field change

PS C:\WINDOWS\system32> Sync-NAVApp -ServerInstance upgBC14 -Name "Base Application" -Version 15.0.36560.36649
Sync-NAVApp : Table OAuth 2.0 Setup :: Unsupported field change. Field:Access Token Due DateTime; Change:Remove
At line:1 char:1
+ Sync-NAVApp -ServerInstance upgBC14 -Name "Base Application" -Version ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$upgBC14/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.M 
   anagement.Cmdlets.SyncNavApp
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e435e27-0b74-7dcd-555d-977517fd3774
* Version Independent ID: ea922161-12f9-3f86-69f9-2044369d6574
* Content: [Upgrade an unmodified application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by krregg** [comment] 2019-10-17 09:01
You should use additional parameter with Sync-NAVApp cmdlet. I got the same error without this parameter. 

` -Mode ForceSync`

**Comment by ManishNAV365** [comment] 2019-10-18 11:10
> You should use additional parameter with Sync-NAVApp cmdlet. I got the same error without this parameter.
>  -Mode ForceSync

Thanks Krreg I did earlier but ForceSync is not a good idea as you fail to know if any other app also losing data. Error is in the Base Table OAuth 2.0 Setup.

**Comment by krregg** [comment] 2019-10-18 11:49
Hi, @ManishNAV365 if I remember right I noticed somewhere the same issue you had and they suggested to do ForceSync.  Besides if you are working on Cronus I don't think this can be a problem in this case, because you don't have any custom modifications in the base app. 

I opened another issue here on Github, where they replied to me saying this: 

> The only issue was in task 6, where a sync error occurred, which required that I use -Mode Forcesync switch (we are also looking into this as a bug as well).

You can read my issue here: https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/791 I hope it will help you. I will work later more on this upgrade case and I will let you know how it went.

**Comment by jswymer** [comment] 2019-10-18 14:24
Hello,
Thanks for the feedback! Thanks for bringing this up. Sorry, I should have mentined this as well, but as you pointed out, it is not recommended practice to use ForceSync because it can result in the loss of data. So it should it should only be used when you are aware of the all the breaking table schema changes that are introduced the extension. We are looking into looking into a resolution to this sync issue. We will keep you posted. Thanks.

**Comment by jswymer** [comment] 2019-10-21 09:50
This issue is caused by the fact that the field "Access Token Due DateTime" was added to table “OAuth 2.0 Setup” in BC14 CU5 (application version 14.6.x.x). However, the base application that is delivered with BC15 (application version 15.0.x.x) does not currently include this field unfortunately. So, when you try to sync the base application with your BC14 CU5 database, a breaking schema change is detected. In the upcoming BC15 CU1, the base application will include the field. Until then, we have changed our guidelines to recommend that you upgrade to BC14 CU4 before upgrading to BC15, or wait until BC15 CU1. If you have already upgraded to BC14 CU5, then you can use -Mode ForceSync. But before doing so, we recommend the sync with the Mode ForceSync first. This will indicate whether there are other destructive changes to be considered. For now, I will close this issue. But if you have additional comments or feedback, feel free to add them to this issue, and we will reopen it as needed. Thanks for the feedback!

**Closed by jswymer** 2019-10-21 09:50 UTC
