### ISSUE TITLE
Better explanation of parameter "Value"

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#746] opened 2019-09-26 12:08 UTC
I tend to double check this out quite often during the years, since the intellisense and compiler is not that helpful with this...

Copied from the old C/AL help file:

```
Specifies what the function should return. The valid options are 1, 2, and 3. 
The value 1 corresponds to Day (1-31).
The value 2 corresponds to Month (1-12).
The value 3 corresponds to Year.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d9137b-ddc5-f248-44f8-da1bd0a3518e
* Version Independent ID: 972423dd-7ea4-70d3-47f2-da5edc4b5fe7
* Content: [Date2DMY Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-date2dmy-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-date2dmy-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-date2dmy-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2019-09-30 12:21
Closing as duplicate.

**Closed by SusanneWindfeldPedersen** 2019-09-30 12:21 UTC

**Comment by dnpb** [comment] 2021-11-01 09:40
Duplicate of what?? This is still a problem:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-date2dmy-method

> Value
> Type: Integer

That tells us precisely nothing.
