### ISSUE TITLE
Task 13 Step 5 - Sync-NAVApp : The metadata object Enum 7000 was not found.

### ISSUE THREAD

**Issue by TorbenBock** [MicrosoftDocs/dynamics365smb-devitpro-pb#1508] opened 2020-10-21 08:18 UTC
When trying to sync the Second version of the table migration extension we get the following error on BC16 CU2 DK: 

Sync-NAVApp : The metadata object Enum 7000 was not found.
At line:2 char:1
+ Sync-NAVApp -ServerInstance $ServerInstanceNEW -Tenant Default -Name  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC160CU1/Default,Microsoft.Dynamics.Nav.Apps.Management.Cm
   dlets.SyncNavApp

The following apps has been published. 

Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
Name          : Base Application
Version       : 14.0.0.0
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 9490c23c-abbb-42eb-8fa5-4664ee23b36b
Name          : TempTableAppV1
Version       : 1.0.0.0
Publisher     : Continia
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 4b915d7e-c02a-435f-85ab-649086c1e002
Name          : Continia Core
Version       : 1.0.0.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 38987ff0-8eec-4232-b379-c7e35ae1b711
Name          : Continia Collection Management 365 (DK)
Version       : 2.0.0.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
Name          : System Application
Version       : 14.0.0.0
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
Name          : Base Application
Version       : 16.2.13509.13779
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 9490c23c-abbb-42eb-8fa5-4664ee23b36b
Name          : TempTableAppV2
Version       : 1.0.1.0
Publisher     : Continia
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
Name          : System Application
Version       : 16.2.13509.13779
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 4b915d7e-c02a-435f-85ab-649086c1e002
Name          : Continia Core
Version       : 3.0.1.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 38987ff0-8eec-4232-b379-c7e35ae1b711
Name          : Continia Collection Management 365 (DK)
Version       : 3.0.2.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : c1335042-3002-4257-bf8a-75c898ccb1b8
Name          : Application
Version       : 16.2.13509.13779
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : ac762be1-e90f-4a72-b519-612a5e3ddc2e
Name          : OIOUBL
Version       : 16.2.13509.13779
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id's in migration.json 
1: System Application
 2: Base Application
 3: Collection Core
 4: Collection

A view of the migration.json file:

{
    "apprules": [
        {
            "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f"
        },
        {
            "id": "437dbf0e-84ff-417a-965d-ed2bb9650972"
        },
        {
            "id": "4b915d7e-c02a-435f-85ab-649086c1e002"
        },
        {
            "id": "38987ff0-8eec-4232-b379-c7e35ae1b711"
        }
    ]
}

**Comment by jswymer** [comment] 2020-10-21 10:49
Hello, This issue might be caused by an error in version 16.2, which was fixed in 16.5. I similar case was discussed on this [Yammer thread](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=867809759592448) thread. I recommend that you contact support to hear about the best course of action. 

Regards,
John

**Comment by TorbenBock** [comment] 2020-10-22 13:25
Hi John
Thanks for your reply. 
We updated to the latest version of BC16 (CU18), and the upgrade went flawless.
So your reply is much appreciated. 

We are writing a help guide for our customers, which helps them to upgrade our solutions.
Now that you knew that the upgrade should be conducted on a BC16 CU5 or newer, do you then also know in which BC15 and BC17 the issue has been fixed, if the issue also is present in these versions?

**Comment by jswymer** [comment] 2020-10-22 14:27
Hi Torben,

You're welcome, I'm glad it worked. The fix is already in 17.0 and later. The fix has not yet been included in 15.X, so if using enum objects, you might experience this problem. 

Regards
John

**Comment by jswymer** [comment] 2020-10-28 13:33
Hello, we have updated the documentation with this known issue. The update will be published soon. We'll close this issue for now, but if you have more feedback on it, let us know. Thanks!

**Closed by jswymer** 2020-10-28 13:33 UTC
Labels: investigating
