### ISSUE TITLE
In a multi-tenant environment, step 7 fails

### ISSUE THREAD

**Issue by peterlinnet** [MicrosoftDocs/dynamics365smb-devitpro-pb#1496] opened 2020-10-14 20:04 UTC
BC16 CU4 OnPrem Multi-tenant 

Step 7 says to mount the new Tenant Database against the Service Tier. However at this point, the new Tenant Database is empty and thus not a "valid Business Central database" as stated it must be by the Mount-NAVTenant docs page.

And as such the Mount fails because the service tier cannot find the [dbo].[$ndo$navappuninstalledapp] table in the tenant database. 

In PowerShell the following error occurs.
`Mount-NAVTenant : The following SQL error was unexpected:
Invalid object name 'dbo.$ndo$navappuninstalledapp'.`

When studying the eventlog the following is found:
`  Database Name: DevExc_BC160Master
  Current Company Name: 
  Statement: SELECT [tenantid], [appid], [version], [name], [publisher], [timeofuninstall], [hasdata] FROM [dbo].[$ndo$navappuninstalledapp]
`

DevExc_BC160Master is the new differently collated tenant database.

What am I missing?

Regards,
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56c1e401-e53b-ffaa-c59e-661eb6145f68
* Version Independent ID: 815fc7a8-950c-60c5-dcd1-4dbe5131c304
* Content: [How to Alter Databases - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-change-database-collation#changing-the-collation-if-extensions-are-installed-on-the-tenant)
* Content Source: [dev-itpro/cside/cside-change-database-collation.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/cside/cside-change-database-collation.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment] 2020-10-20 14:36
Hello, I tried this procedure on a 16.4 and 16.5 version, but couldn't reproduce your issue. I was able to create new empty database and mount it successfully. Not sure if there is more other info you can provide, otherwise I recommend you contact Microsoft support.

**Comment by peterlinnet** [comment] 2020-10-21 08:50
Hi jswymer,

Thanks for your time. I've run the following to re-test the step and can reproduce the error.

`New-AzureRmSqlDatabase -ResourceGroupName myazureresourcegroup -ServerName myazuresqlserver -DatabaseName TestEmptyTenant -ElasticPoolName myazuresqldbpool -Collation Danish_Greenlandic_100_CS_AS`
`Mount-NAVTenant BC160 -DatabaseName TestEmptyTenant -DatabaseCredentials (Get-Credential) -Tenant TestEmptyTenant`

Did you try it on a true multitenant setup and using Azure SQL-DBs?

I worked around the problem by using Create-NAVDatabase and Remove-NAVApplication on my local SQL-server and afterwards "Deploy Database to Microsoft Azure SQL Database" from SQL Server Management Studio. The resulting Azure SDQL database from that drill mounted OK.

Regards,
Peter

**Comment by jswymer** [comment] 2020-10-21 09:38
Hi Peter,

Sorry, I did not run it on Azure SQL DBs. It was done on a local installation with SQL Server. I will pass this info on to the dev team to see if they have any input. I'll let you know.

**Comment by jswymer** [comment] 2020-10-29 10:10
Hi Peter,

I finally got a chance to try using Azure SQL DBs. I tried two scenarios, which both worked.

In the first scenario, I created an empty tenant database with the new collation locally in locally SQL Server, then exported/imported data tier to create it on Azure SL. Then, I was able to mount it.

For the second scenario, I created an empty database with the new collation directly in Azure SQL using PowerShell, then mounted it against the application db.

**Comment by jswymer** [comment] 2020-11-12 16:01
Hi Peter, I hope the information was helpful. I will close this issue for now. But If you have more feedback, let me know and I'll reopen it. Thanks.

**Closed by jswymer** 2020-11-12 16:01 UTC
Labels: investigating

**Comment by peterlinnet** [comment] 2020-11-12 16:33
Thanks, I never got back to it. As mentioned I found a workaround.
I still don’t understand why you managed complete the process and I didn’t, but never mind. Hopefully I’ll never have to do it again, and hopefully no one else will encounter my problem.


Med venlig hilsen


Peter Linnet

[ecodel_logo_graf_pos_rgb]

Telefon: 51 94 98 74, Skype for Business: pli@ecodel.com
Mail: pli@ecodel.com<mailto:pli@ecodel.com>, Web: www.ecodel.com<http://www.ecodel.com/>
Onlinesupport: https://get.teamviewer.com/erphotel
