### ISSUE TITLE
RequestFilterFields

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#839] opened 2019-11-11 13:18 UTC
It seems that, contrary to runing a report in Windows Client filter tabs are not displayed in Web Client if RequestFilterFields is nit defined. Could there please be made a note that one needs to define RequestFilterFields to have filter tab(s) on RequestPage on Web Client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ef1902-e011-3732-213b-14c1a1f2c54e
* Version Independent ID: 27da945e-d357-9543-d8f0-d651f8cc08af
* Content: [Request Pages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-request-pages)
* Content Source: [dev-itpro/developer/devenv-request-pages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-request-pages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment] 2019-11-11 13:22
#840 relates to this.

**Comment by SusanneWindfeldPedersen** [comment] 2019-12-10 09:11
Thanks, closing this as duplicate of #840

**Closed by SusanneWindfeldPedersen** 2019-12-10 09:11 UTC

**Comment by lvanvugt** [comment] 2019-12-10 09:16
Hi Susanne, I do not agree that it is a duplicate, that's why I recorded two issues. If your argument is that you can solve it with one issue I agree.

**Comment by SusanneWindfeldPedersen** [comment] 2019-12-10 09:21
Hi Luc, I did make a note that you filed an issue on two different topics - so we'll keep that in mind when solving it to make sure that notes are discoverable from both topics. Hope that sounds reasonable. Thanks.
