### ISSUE TITLE
BC14 to 17.2 - The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.

### ISSUE THREAD

**Issue by isatahiri** [MicrosoftDocs/dynamics365smb-devitpro-pb#1611] opened 2020-12-25 00:56 UTC
Hello,

I'm having trouble when upgrading from BC14 CU 18 to BC17.2. 
The issue is happing in [Task 12](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17)

All these tables are new and do not have data inside. I checked the generated Al files, there are no errors or warnings.
This a migration from NAV 2013R2 initially. I followed this path :

NAV2013R2 --> NAV 2018 -->BC14 CU18 --> BC17.2 and then BC Online hosted by MS.  

I'm a bit out of options here. Deleting the table at source --> Error on compilation to other objects. 
Any suggestions will be welcome.

```
ERROR on runnign command :  Sync-NAVApp -ServerInstance bc170 -Name "bc14baseapptablesonly" -Version 1.0.0.1
-------
Table VAT Reg. No. Srv. Template :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table VAT Reg. No. Srv. Template :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table VAT Registration Log Details :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table VAT Registration Log Details :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table Swiss QRBill Buffer :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table Swiss QRBill Buffer :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table Swiss QRBill Billing Detail :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table Swiss QRBill Billing Detail :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table Swiss QRBill Billing Info :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table Swiss QRBill Billing Info :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table Swiss QRBill Layout :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table Swiss QRBill Layout :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table Swiss QRBill Reports :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table Swiss QRBill Reports :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
Table Swiss QRBill Setup :: The previous primary key 'Key1' cannot be located. Changing the primary key is not allowed.
Table Swiss QRBill Setup :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key 'Key1' the primary key again.
----------
```
```
Schema --> NAV 2018 & BC 14

Swiss QRBill Setup keys ----> {key(Key1; "Primary key"){Clustered = true;}}
Swiss QRBill Reports keys ----> {key(Key1; "Report Type"){Clustered = true;}}
Swiss QRBill Layout ----> keys{key(Key1; "Code"){Clustered = true;}}
Swiss QRBill Billing Info ----> keys {key(Key1; "Code"){Clustered = true;}}
Swiss QRBill Billing Detail keys ----> { key(Key1; "Entry No.") {Clustered = true; }}
Swiss QRBill Buffer ----> keys{key(Key1; "Entry No."){Clustered = true;}}
VAT Registration Log Details ----> keys{key(Key1; "Entry No."){Clustered = true;}}
VAT Reg. No. Srv. Template --> keys { key(Key1; "Code") { Clustered = true; } }
```
```
Schema 17.2
Swiss QRBill Setup ----> {key(PK; "Primary key"){Clustered = true;}} --> Table 'Swiss QRBill Setup' is removed. Reason: moved to Swiss QR-Bill extension table 11512 Swiss QR-Bill Setup.
Swiss QRBill Reports ----> {key(PK; "Report Type"){Clustered = true;}} --> Table 'Swiss QRBill Reports' is removed. Reason: moved to Swiss QR-Bill extension table 11514 Swiss QR-Bill Reports.
Swiss QRBill Layout ----> keys{key(PK; "Code"){Clustered = true;}} --> Table 'Swiss QRBill Layout' is removed. Reason: moved to Swiss QR-Bill extension table 11513 Swiss QR-Bill Layout.
Swiss QRBill Billing Info ----> keys {key(PK; "Code"){Clustered = true;}} --> Table 'Swiss QRBill Billing Info' is removed. Reason: moved to Swiss QR-Bill extension table 11511 Swiss QR-Bill Billing Info.
Swiss QRBill Billing Detail keys ----> { key(Key1; "Entry No.") {Clustered = true; }} --> Table 'Swiss QRBill Buffer' is removed. Reason: moved to Swiss QR-Bill extension table 11510 Swiss QR-Bill Buffer.
Swiss QRBill Buffer ----> keys{key(PK; "Entry No."){Clustered = true;}}
VAT Registration Log Details ----> keys {key(PK; "Log Entry No.", "Field Name"){Clustered = true;}}
VAT Reg. No. Srv. Template --> keys {key(PK; Code) { Clustered = true;}}
```

**Comment by DigiTecKid** [comment] 2021-01-26 15:33
Can someone point us in the right direction on how to handle these table errors?  I'm getting an error with some of the same tables in the same upgrade path at the same step.

I'm upgrading from NAV 2013 to BC17 and have run into the errors listed below in part of the upgrade from [BC14 to BC17](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17) in upgrade [Task 12](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17#task-12-synchronize-final-extensions) Step 6 - Sync-NAVApp on the "Second version of the table migration extension (empty version)".

_"Sync-NAVApp : Table VAT Reg. No. Srv. Template :: The previous primary key 'Key1' cannot be located. Changing the
primary key is not allowed.
Table VAT Reg. No. Srv. Template :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key
'Key1' the primary key again.
Table VAT Registration Log Details :: The previous primary key 'Key1' cannot be located. Changing the primary key is
not allowed.
Table VAT Registration Log Details :: Introducing a new key 'PK' as the primary key is not allowed. Please make the
key 'Key1' the primary key again.
Table Approval Setup :: The table 'Approval Setup' cannot be located. Removing tables is not allowed unless they are
temporary or are being moved by migration to another app.
Table Approval Code :: The table 'Approval Code' cannot be located. Removing tables is not allowed unless they are
temporary or are being moved by migration to another app.
Table Approval Templates :: The table 'Approval Templates' cannot be located. Removing tables is not allowed unless
they are temporary or are being moved by migration to another app.
Table Additional Approvers :: The table 'Additional Approvers' cannot be located. Removing tables is not allowed
unless they are temporary or are being moved by migration to another app.
Table DO Payment Setup :: The table 'DO Payment Setup' cannot be located. Removing tables is not allowed unless they
are temporary or are being moved by migration to another app.
Table DO Payment Card Type :: The table 'DO Payment Card Type' cannot be located. Removing tables is not allowed
unless they are temporary or are being moved by migration to another app.
Table Mini Pages Mapping :: The table 'Mini Pages Mapping' cannot be located. Removing tables is not allowed unless
they are temporary or are being moved by migration to another app.
Table Integration Page :: The table 'Integration Page' cannot be located. Removing tables is not allowed unless they
are temporary or are being moved by migration to another app."_

**Comment by isatahiri** [comment] 2021-01-26 20:05
Hello,
#1613 was the best hint. Make sure that you are runing the local migration tools. I had a nightmare trying to repare stuff because I used the upgrade toolkit. All my tables were empty so I removed them. Hope this helps.

**Comment by DigiTecKid** [comment] 2021-01-27 17:40
Thank you for your reply Isa!  I am running only local databases and local migration tools, all NA.

I'm seeing this as an internal process error from the upgrade documentation Microsoft has supplied.

Based on the documentation:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17#task-12-synchronize-final-extensions


Here are the errors I get from Task 12 Step 6 and the SQL tables I find the in the upgrade database:

Table Integration Page :: The table 'Integration Page' cannot be located. Removing tables is not allowed unless they are temporary or are being moved by migration to another app."
Integration Page$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table Additional Approvers :: The table 'Additional Approvers' cannot be located. Removing tables is not allowed
unless they are temporary or are being moved by migration to another app.
Client, Inc_$Additional Approvers$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table Approval Code :: The table 'Approval Code' cannot be located. Removing tables is not allowed unless they are
temporary or are being moved by migration to another app.
Client, Inc_$Approval Code$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table Approval Setup :: The table 'Approval Setup' cannot be located. Removing tables is not allowed unless they are
temporary or are being moved by migration to another app.
Client, Inc_$Approval Setup$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table Approval Templates :: The table 'Approval Templates' cannot be located. Removing tables is not allowed unless
they are temporary or are being moved by migration to another app.
Client, Inc_$Approval Templates$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table DO Payment Card Type :: The table 'DO Payment Card Type' cannot be located. Removing tables is not allowed
unless they are temporary or are being moved by migration to another app.
Client, Inc_$DO Payment Card Type$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table DO Payment Setup :: The table 'DO Payment Setup' cannot be located. Removing tables is not allowed unless they
are temporary or are being moved by migration to another app.
Client, Inc_$DO Payment Setup$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table Mini Pages Mapping :: The table 'Mini Pages Mapping' cannot be located. Removing tables is not allowed unless
they are temporary or are being moved by migration to another app.
Client, Inc_$Mini Pages Mapping$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table VAT Reg. No. Srv. Template :: The previous primary key 'Key1' cannot be located. Changing the
primary key is not allowed.
Table VAT Reg. No. Srv. Template :: Introducing a new key 'PK' as the primary key is not allowed. Please make the key
'Key1' the primary key again.
Client, Inc_$VAT Reg_ No_ Srv_ Template$437dbf0e-84ff-417a-965d-ed2bb9650972
Client, Inc_$VAT Reg_ No_ Srv_ Template$fd469a13-f4cb-43af-b7b6-56323ed9085f

Table VAT Registration Log Details :: The previous primary key 'Key1' cannot be located. Changing the primary key is
not allowed.
Table VAT Registration Log Details :: Introducing a new key 'PK' as the primary key is not allowed. Please make the
key 'Key1' the primary key again.
Client, Inc_$VAT Registration Log Details$437dbf0e-84ff-417a-965d-ed2bb9650972
Client, Inc_$VAT Registration Log Details$fd469a13-f4cb-43af-b7b6-56323ed9085f


Here are the steps that are related to the App ID's specified in the SQL tables created in the SQL database by the migration/upgrade functionality:
Task 2: Create table migration extension
	Create the first version
		AppName:  TableMigrationBC14toBC17
		AppId:  fd469a13-f4cb-43af-b7b6-56323ed9085f
		Versions:  1.0.0.0
		App:  DEV_TableMigrationBC14toBC17_1.0.0.0.app  (With Tables)
	Create the second version
		AppName:  TableMigrationBC14toBC17
		AppId:  fd469a13-f4cb-43af-b7b6-56323ed9085f
		Versions:  1.0.0.1
		App:  DEV_TableMigrationBC14toBC17_1.0.0.1.app  (Without Tables)

Task 3: Create empty extensions System, Base, and customization extensions
	AppName:  Microsoft Base Application
	AppId: 437dbf0e-84ff-417a-965d-ed2bb9650972
	Version:  14.0.0.0

Task 6 Step 2:
	Set-NAVServerConfiguration -ServerInstance bc170 -KeyName "DestinationAppsForMigration" -KeyValue '[{"appId":"fd469a13-f4cb-43af-b7b6-56323ed9085f", "name":"TableMigrationBC14toBC17", "publisher": "DEV"}]'

Task 8 Step 2:
	Publish-NAVApp -ServerInstance bc170 -Path "C:\Users\james\Documents\AL\TableMigrationBC14toBC17\DEV_TableMigrationBC14toBC17_1.0.0.0.app" -SkipVerification

Task 8 Step 3:
	Publish-NAVApp -ServerInstance bc170 -Path "C:\Users\james\Documents\AL\MicrosoftBaseApplicationForUpgrade\Microsoft_Base Application_14.0.0.0.app" -SkipVerification

Task 9 Step 3a:
	Sync-NAVApp -ServerInstance bc170 -Tenant default -Name "TableMigrationBC14toBC17" -Version 1.0.0.0

Task 11 Step 1:
	Publish-NAVApp -ServerInstance bc170 -Path "C:\Users\james\Documents\AL\TableMigrationBC14toBC17\DEV_TableMigrationBC14toBC17_1.0.0.1.app" -SkipVerification

Task 12 Step 6:
	Sync-NAVApp -ServerInstance bc170 -Tenant default -Name "TableMigrationBC14toBC17" -Version 1.0.0.1

**Comment by jswymer** [comment] 2021-02-08 13:24
Hello,

Thanks for the feedback. As for the removed table errors, I'll have to look into to this a bit. Regarding the key-related errors, there's a key-naming issue, which will cause problems when upgrading to the Microsoft Base Application.

In some local versions, like CH and NA, new table objects were added as part of a minor update. In version 14, which is still C/AL based, the primary keys of these tables are unnamed. In version 15, 16, and 17, which is fully AL-based, these tables have been moved to extensions, and the primary keys have the name `PK`.  The problem is that when you convert the version 14 table objects to AL using the txt2AL, the primary keys are given the name `Key1`. This introduces breaking changes when upgrading to version 15, 16, or 17 because of the mismatch between `Key1` and `PK` primary key names.

The affected local versions and table include:

|Local 14 version|Tables|
|-------------|------|
|CH|<ul><li>QRBill Buffer</li><li>QRBill Billing Detail</li><li>QRBill Billing Info</li><li>QRBill Layout QRBill</li><li>QRBill Setup</li><li>VAT Reg. No. Srv. Template</li><li>VAT Registration Log Details</li></ul>|
|NA|<ul><li>VAT Reg. No. Srv. Template</li><li>VAT Registration Log Details</li></ul>|

To avoid these errors, after converting the version 14 tables to AL, rename instances of the primary key `Key1 ` to `PK` in the affected table objects. Then, build the first version of the table migration extension. We will update the documentation accordingly.

**Comment by DigiTecKid** [comment] 2021-02-08 22:25
Changing the key name from Key1 to PK in tables:
table 226 "VAT Reg. No. Srv. Template"
table 227 "VAT Registration Log Details"
Fixed the errors I was getting for those tables.
[cid:image001.png@01D6FE3F.57661170]

To fix the other errors - “Removing tables is not allowed unless they are temporary or are being moved by migration to another app.”
I put obsolete tags in the tables reporting this error but it did not fix this error.

[cid:image002.png@01D6FE3F.57661170]

[cid:image003.png@01D6FE3F.57661170]


Best Regards
James Reynolds | Dynamic Technology Partners
James@dynatechpartners.com<mailto:James@dynatechpartners.com> | T: +1 407 767 0025 | M: +1 407 925 3434
Contact Me On Microsoft Teams<https://teams.microsoft.com/l/chat/0/0?users=james@dynatechpartners.com>
Dynamic Technology Partners Web Site<http://www.dynatechpartners.com/>
[cid:image004.png@01D6FE3F.57661170]

**Comment by jswymer** [comment] 2021-02-16 16:55
Hello,
I would have expected the other objects to be covered by the upgrade toolkits for BC 14 and earlier. I noticed the Approval Templates, Approval Setup, Approval Code, and Additional Approvers seem to be included in the upgrade toolkit codeunits. Perhaps you should contact Support to get a resolution and some guidance.  Regards

**Comment by jswymer** [comment] 2021-02-24 07:11
Hello, We'll close this issue for now but if you have additional feedback, we'll gladly open it again. Thanks for the all the input.

**Closed by jswymer** 2021-02-24 07:11 UTC
