### ISSUE TITLE
Property IndentationControl

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#1337] opened 2020-07-27 14:29 UTC
The Property **IndentationControl** seems to have no effect anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4757480a-c03f-22fb-a7cb-158e73e49282
* Version Independent ID: 787b31f8-39a7-a85c-9130-38fae7c6eb9a
* Content: [IndentationControls Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-indentationcontrols-property)
* Content Source: [dev-itpro/developer/properties/devenv-indentationcontrols-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-indentationcontrols-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment] 2020-07-28 06:57
Hello, Thanks for the feedback.

This issue seems to be a duplicate of issue [1336](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1336). So, I will close this issue, and use 1336 for tracking.

**Closed by jswymer** 2020-07-28 06:57 UTC

**Comment by DanielGoehler** [comment] 2020-07-28 06:59
@jswymer: I wanted to make sure that all articles get updated.
