### ISSUE TITLE
Web links are not working.

### ISSUE THREAD

**Issue by KellTechServices** [MicrosoftDocs/dynamics365smb-devitpro-pb#1292] opened 2020-07-08 10:49 UTC
Regarding: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-transition-business-central

When clicking on any link in the Asset column, I am prompted to sign in with a Microsoft account.  After doing so, I recieve the following Runtime error for every link:

Server Error in '/' Application.
Runtime Error
Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a3feb1-2f95-a046-f60b-e413fce8cd96
* Version Independent ID: b3915761-5fb8-bd67-e837-645aaf734525
* Content: [Transitioning to Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-transition-business-central)
* Content Source: [dev-itpro/developer/readiness/readiness-transition-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-transition-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by SusanneWindfeldPedersen** [comment] 2020-07-09 07:32
Hello, I cannot reproduce this error. Do you have a Microsoft account? Can you please try using sign in with a different account? Thanks.

**Comment by SusanneWindfeldPedersen** [comment] 2020-07-10 09:29
Closing this issue. The links should be working correctly. Thanks.

**Closed by SusanneWindfeldPedersen** 2020-07-10 09:29 UTC
