### ISSUE TITLE
Task 8: Upgrade the tenant data get stuck on 66,67%

### ISSUE THREAD

**Issue by krregg** [MicrosoftDocs/dynamics365smb-devitpro-pb#791] opened 2019-10-17 14:10 UTC
I have a case where I am trying to upgrade the default Cronus database to the new version 15. 

I am using this document: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application)

Anyway, I did like this. I started with performing this command `Start-NAVDataUpgrade -ServerInstance BC150 -Tenant default -FunctionExecutionMode Serial -SkipAppVersionCheck -Force`, and after a few minutes, I check the progress with the command `Get-NavDataUpgrade -Progress -ServerInstance BC150` where I can see that the progress is stuck on 66,67% and it doesn't move anywhere. 

I have no idea why this happens. I tried to do it many, many, many times and every time the same result, the progress at `Start-NAVDataUpgrade` gets stuck. I tried with my own database and with a fresh Cronus copy, the result is the same (I tried at least 3 times on Cronus). 

There is one thing also I noticed:

`Task 7: Install system application and base application extensions` is one task before where I get stuck. This step can't be done as a 7th step. If I understand right after you perform `Publish-NAVApp`, `Sync-NAVTenant` and `Sync-NAVApp` it should be a step for Data Upgrade and not Install as its mentioned. Install is not possible before that, and also it says that when you run `Start-NAVDataUpgrade` it will automatically install System and Base application, which should be installed one step before if I read MS instructions. That's confusing. 

Anyone else noticed this or is it just me with a case like this?

When I install System and Base Application on my tenant the information about installed apps looks like that:

```
Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
Name          : System Application
Version       : 15.0.36560.36649
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global

Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
Name          : Base Application
Version       : 15.0.36560.36649
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
```

I have to mention that before I started upgrading Business Central from 14 to 15 I installed the latest CU6, as required in here [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application).

I downloaded BC latest version from partner source and I am more than sure that I prepared everything right before starting the upgrade (installing CU6 on sprint version, or installing BC CU6 directly, I tried both). I have a feeling that MS instructions are wrong.

Please let me know if anyone else encountered the same problems as me, or I hope that there some explanation for this on internet or it will be soon because for now, I have no idea what to do.

**Comment by jswymer** [comment] 2019-10-18 08:00
Hello. Thanks for the feedback!

On the issue regarding Start-NAVDataUpgrade and the process getting stuck under 100%, we have experienced this issue in-house and currently have a bug to investigate. In the cases we have seen, the upgrade process had in fact completed and a restart of the server instance showed the upgrade to be at 100%. 

In Task 8, the statement that Start-NAVDataUpgrade installs the System and Base Applications is wrong and will be removed the next time we publish the article. 

As for task 7, you should be able to install the system and base application extensions at this point. I just successfully ran through all tasks and steps in the documented order. The only issue was in task 6, where a sync error occurred, which required that I use -Mode Forcesync switch (we are also looking into this as a bug as well).

**Comment by krregg** [comment] 2019-10-18 08:28
Thank you @jswymer for your answer. 

Today I tried to do the whole process once again. I started with a clean BC14 CU6 Cronus installation. I followed the instructions as you are saying, I fixed the 6th step and I was somehow able to install System and Base application (no errors at installing this time). All ok until the 8th step.

Now I tried to execute `Start-NAVDataUpgrade` and then I wanted to check the progress with the command `Get-NavDataUpgrade -ServerInstance BC150 -Progress` and it doesn't want to show me the progress bar anymore and I am not sure whats the progress really. Anyway, after a while I tried to reach `http://localhost:8080/BC150/` but I am getting `HTTP Error 404.0 - Not Found`.

I am not sure what I am doing wrong, should I wait for a bug fix or what else can I do in my case?
I thought the upgrade will work smoothly with the Cronus demo database.

ps. I noticed one thing when executing `Start-NAVDataUpgrade` in EventViewer exists a warning which is saying: `Exclusive tenant action scope is not supported if this server instance is not configured for multi-tenancy. Change the Multitenant setting to true in the server configuration to enable multi-tenancy on this server.` I am using a single tenant in my case.

This are the commands I run in BC Admin Console (BC150 side) after I unpublish all extensions (on BC140 side):
```
Invoke-NAVApplicationDatabaseConversion -DatabaseServer NL-SI-X09426\MSSQL17TEST -DatabaseName nav14cu6
Set-NAVServerConfiguration -ServerInstance BC150 -KeyName DatabaseName -KeyValue nav14cu6
Set-NavServerConfiguration -ServerInstance BC150 -KeyName "EnableTaskScheduler" -KeyValue false
Import-NAVServerLicense BC150 -LicenseFile "C:\Users\gregor.soln\Documents\AL Extra\licence for NAV DEVEL\Maia365-DEV.flf"
Restart-NAVServerInstance -ServerInstance BC150
Publish-NAVApp -ServerInstance BC150 -Path "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\150\AL Development Environment\System.app" -PackageType SymbolsOnly
Publish-NAVApp -ServerInstance BC150 -Path "C:\backup\Dynamics 365 Business Central 2019 Release Wave 2.W1.36649\Applications\System Application\Source\Microsoft_System Application.app"
Publish-NAVApp -ServerInstance BC150 -Path "C:\backup\Dynamics 365 Business Central 2019 Release Wave 2.W1.36649\Applications\BaseApp\Source\Microsoft_Base Application.app"
Sync-NAVTenant -ServerInstance BC150 -Mode Sync -Tenant default
Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "System Application" -Version 15.0.36560.36649 -Mode ForceSync -Force
Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "Base Application" -Version 15.0.36560.36649 -Mode ForceSync -Force
Install-NAVApp -ServerInstance BC150 -Name "System Application" -Version 15.0.36560.36649
Install-NAVApp -ServerInstance BC150 -Name "Base Application" -Version 15.0.36560.36649
Start-NAVDataUpgrade -ServerInstance BC150 -FunctionExecutionMode Serial -SkipAppVersionCheck -Force
```

**Comment by jswymer** [comment] 2019-10-18 08:56
Hello, perhaps the progress does not show because the upgrade process was completed and at 100%. The same happened for me. When I ran Get-NAVDataUpgrade BC150, it returned:
`ExtensionData             : System.Runtime.Serialization.ExtensionDataObject
TenantId                  : default
TotalFunctionCount        : 9
ExecutedFunctions         : 9
UpgradeExecutionMode      : UsingParallelOrSerialTransaction
Progress                  : 100.00 %
Details                   : {OnRun}
Errors                    :
ExecutionDetails          : {BASE, BASE, BASE, BASE...}
ExecutionErrors           :
State                     : Completed
NumericProgress           : 1
IsTenantInExclusiveAccess : False`

Maybe you can try this to see what you get. Also, try Get-NAVTenant bc150 -Tenant default -ForceRefresh and see what the state is. 

As for the event log warning, I got the same warning so I think you can ignore this. 

Even without the data upgrade, you should be able to open the Web client, as long as the Web server instance is running.

**Comment by jswymer** [comment] 2019-10-18 14:28
Hello, 

Thanks again for the feedback. As pointed out in the issue 774, it is not recommended practice to use ForceSync because it can result in the loss of data. So it should only be used when you are aware of the all the breaking table schema changes that are introduced the extension. Sorry for not mentioning it earlier. We are looking into a resolution to this sync issue. We will keep you posted. Thanks.

**Comment by jswymer** [comment] 2019-10-21 09:50
This issue is caused by the fact that the field "Access Token Due DateTime" was added to table “OAuth 2.0 Setup” in BC14 CU5 (application version 14.6.x.x). However, the base application that is delivered with BC15 (application version 15.0.x.x) does not currently include this field unfortunately. So, when you try to sync the base application with your BC14 CU5 database, a breaking schema change is detected. In the upcoming BC15 CU1, the base application will include the field. Until then, we have changed our guidelines to recommend that you upgrade to BC14 CU4 before upgrading to BC15, or wait until BC15 CU1. If you have already upgraded to BC14 CU5, then you can use -Mode ForceSync. But before doing so, we recommend the sync with the Mode ForceSync first. This will indicate whether there are other destructive changes to be considered. For now, I will close this issue. But if you have additional comments or feedback, feel free to add them to this issue, and we will reopen it as needed. Thanks for the feedback!

**Closed by jswymer** 2019-10-21 09:50 UTC
