### ISSUE TITLE
Does not apply to Page Part

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2785] opened 2023-03-01 19:27 UTC
Current article lists Page Part as applicable. When adding AboutText or AboutTitle to a CardPart, you get warning AW0012 that says that's not allowed.

The same applies to AboutTitle: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-abouttitle-property

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d662c9b2-8f4d-ae0f-ee34-d71a8e3567d3
* Version Independent ID: 18c749aa-32de-e63d-bcc7-fcd262fba1c6
* Content: [AboutText Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-abouttext-property)
* Content Source: [dev-itpro/developer/properties/devenv-abouttext-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-abouttext-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2023-04-18 08:38
Thanks for the feedback, this sounds like a product bug - the topic is autogenerated from source code with all of the supported objects. We'll create a bug and close this issue. Thanks.

**Closed** 2023-04-18 10:47 UTC
Labels: bug

**Comment by EmilDamsbo** [comment] 2023-04-20 10:57
This is not a bug in the documentation. As of release 2022 Wave 2 corresponding to version 10 of the compiler, this rule is no longer reporting diagnostics for CardParts or ListParts. If you experience this issue in future for versions newer than 10, I recommend you open a bug about it on the AL language repository instead, as that would be considered a bug in the extension.
