### ISSUE TITLE
Sync-NAVTenant Error

### ISSUE THREAD

**Issue by kimsong-bti** [MicrosoftDocs/dynamics365smb-devitpro-pb#1348] opened 2020-08-01 04:03 UTC
Sync-NAVTenant : An item with the same key has already been added.
At line:1 char:1
+ Sync-NAVTenant -ServerInstance BC160 -Mode ForceSync
+ ---------------------------------------------------------------------
+ CategoryInfor: NotSpecified.............

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515f9e0a-25ac-5dfd-ede3-a3887518cfe4
* Version Independent ID: b1d600c7-6985-df9e-b965-25afb9c6f0f2
* Content: [Technical Upgrade From Version 14 to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v16)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v14-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment] 2021-02-08 15:23
Hello, thanks for the feedback.

I cannot reproduce this error, but perhaps I've misunderstood something. Sorry for the long delay. We will close this issue for now, but if you have more feedback, we'll be happy to reopen it.

**Closed by jswymer** 2021-02-08 15:23 UTC
