### ISSUE TITLE
Property IndentationControl

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#1339] opened 2020-07-27 14:29 UTC
The Property **IndentationControl** seems to have no effect anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4833ee8-8e6f-cd0e-5abe-e81ea823089c
* Version Independent ID: b8e59ef9-ecc6-effe-8d94-dbe7003d2a3c
* Content: [Designing Indented Hierarchy Lists - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-indented-hierarchy-lists)
* Content Source: [dev-itpro/developer/devenv-indented-hierarchy-lists.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-indented-hierarchy-lists.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment] 2020-07-28 06:56
Hello, Thanks for the feedback.

This issue seems to be a duplicate of issue [1336](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1336). So, I will close this issue, and use 1336 for tracking.

**Closed by jswymer** 2020-07-28 06:56 UTC

**Comment by DanielGoehler** [comment] 2020-07-28 06:59
@jswymer: I wanted to make sure that all articles get updated.
