### ISSUE TITLE
Translation for TableExtension and PageExtension

### ISSUE THREAD

**Issue by RaKuNbg** [MicrosoftDocs/dynamics365smb-devitpro-pb#861] opened 2019-11-18 10:48 UTC
I have created a TableExtension and a PageExtension to view the new field on a standard card page.
Then I added the translation for the TableExtension in the xliff-file.
I expected that this translation is also used in the PageExtension to show the translation on the card page.
But it seems that I have to add the translation also for the PageExtension.
==&gt; Is this correct or am I doing something wrong?
==&gt; If it is correct, are there any plans to change this so I have to put the translation only at one place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by thpeder** [comment] 2019-11-20 14:48
Duplicate of #860

The caption of the table field is used on the page control if it hasn't been overwritten by either the caption of the page control or an external translation.

**Closed** 2019-11-21 06:57 UTC
Labels: investigating
