### ISSUE TITLE
Enums extending standard Option fields

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#386] opened 2019-02-05 12:54 UTC
Hi Susanne,

I'm afraid this time the trial and error method is driving me crazy... 
I've reached a point in my refactoring where I must extend several standard option fields.
After reading this help page several times, I'm still lost :-(
Let's pick ReportSelections.Usage as an example:
According to this page, the first thing to do is modify the field in C/SIDE:
Extensible: easy - change it to true
EnumeTypeId: what am I supposed to put here? 77? 50###? (what if I want to request it on GitHub? Should I really decide this value for the base Enum?)
EnumTypeName I understand it should be some logical name but then again I find it strange that I should decide on this. To continue, let's suppose I put RepSelUsage.

Then what? the page doesn't address the rest of the task...

I've tried the following and none of it works:

1) I create only an enumextension in the following way:
enumextension 50001 EYR_RepSelUsage extends RepSelUsage
{
value(50000;EYR_Report1) { Caption = ‘Whatever’;}
}
Result: Error AL0999: Internal error: System.NullReferenceException: Object reference not set to an instance of an object.[...] Error: The package could not be created.

2) I maintain my enumextension, but also add a definition for RepSelUsage in the following way (specifying all existing members):
enum 77 RepSelUsage
{
Extensible = true;
value(0; S.Quote) { Caption = ‘Sales Quote’;}
value(1;S.Order) { Caption = ‘Sales Order’;}
[…]
}
Result: Error AL0264: An application object of type 'Enum' with ID '77' is already declared.

3) Same as No. 2, but I change "enum 77 RepSelUsage" to "enum 50000 RepSelUsage" 
Result: Error AL0197: An application object of type 'Enum' with name 'RepSelUsage' is already declared.

4) I remove my enumextension, and instead add the following to the end of my definition for the Enum:
value(50000;EYR_Report1) { Caption = ‘Whatever’;}
Result: same as No. 3 (Error AL0197)

Please complete this topic so that it's clear how to extend standard option fields

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd55bfe-2599-257c-fe83-6c5c7d90b04b
* Version Independent ID: 60ac2b4a-d10a-5e8c-d2e7-ac380943cd0b
* Content: [Extensible Enums - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)
* Content Source: [dev-itpro/developer/devenv-extensible-enums.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extensible-enums.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2019-02-06 08:46
Hi, this is a duplicate of the thread on Yammer - I've included Esben on that thread to answer any questions. And it seems that this might be a product bug. Are you okay with me closing this and then we'll continue on Yammer? Thanks.

**Comment by Bleika** [comment] 2019-02-06 16:31
Yes - time is really pressing on this one so in the end I decided to publish it in both channels.

What remains is that this particular page could be richer in content about when it comes to extending standard fields (I think it's clear enough about creating your own enums). 
Also, as @kine already pointed out 3 months ago, there's not much about using them in code either (the foo-p example isn't too clear).
As I said on Yammer - I reached out to some colleagues and they were in the same situation (postponing this issue because the didn't find this topic clear at all).

Since Esben already confirmed that my first attempt was the right one, I'd propose you use this as an opportunity to enrichen this page (even if it comes with a footnote about availability and the spring release...) 
Apart from that, I'm OK with closing this issue here.

**Closed** 2019-02-11 11:31 UTC

**Comment by AbsolutelyFreeWeb** [comment] 2019-06-06 15:12
@SusanneWindfeldPedersen @Bleika I did not know there is a second channel for reporting things. Could you let me know what yammer channel I am missing participating in ?

**Comment by edupont04** [comment] 2019-06-07 08:20
Hi AbsolutelyFreeWeb,
We recommend that you join the Ready to Go programme for access to additional resources. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-ready-to-go?tabs=learning

**Comment by grosugeorge** [comment] 2019-07-31 13:10
Hi @edupont04,
Can you help me with the link to the Yammer thread?
