### ISSUE TITLE
Error in "Tip" baloon

### ISSUE THREAD

**Issue by Illeris** [MicrosoftDocs/dynamics365smb-devitpro-pb#2690] opened 2023-01-06 20:57 UTC
[Enter feedback here]

Dear,

The "Tip" baloon says:

You can get the flow and environment IDs in Power Automate. Sign in to [Power Automate](https://powerautomate.com/) and open the flow for editing. Then, get the environment ID and flow ID from the URL in the browser address, which has a format like: https://make.powerautomate.com/environments/<environment ID>/flows/<environment ID>.

However, I believe the URL should be 

https://make.powerautomate.com/environments/<environment ID>/flows/<flow ID>.

Please revise. Sorry if I'm mistaken

Thx
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0903ee-16c0-6173-2805-a9dc2cb85299
* Version Independent ID: ca99a227-03fa-abea-d16a-c3d042f888e6
* Content: [Actions overview - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-actions-overview)
* Content Source: [dev-itpro/developer/devenv-actions-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-actions-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2023-01-11 08:02
Thanks for the feedback. I can't reproduce this issue. The URLs above look the same to me. The suggested URL in the article: https://make.powerautomate.com/environments/<environment ID>/flows/<environment ID> seems to be correct.

**Comment by SusanneWindfeldPedersen** [comment] 2023-01-13 13:38
Closing this, as we cannot repro - please open a new issue if this is not resolved. Thanks.

**Closed by SusanneWindfeldPedersen** 2023-01-13 13:38 UTC
Labels: investigating
