### ISSUE TITLE
Confusion on "Edit in Excel"

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#804] opened 2019-10-24 08:58 UTC
The point "Read/write data with Excel add-in" above states categorically that the "Edit in Excel" is not available in premise.  However the page "Viewing and Editing in Excel From Business Central" (https://docs.microsoft.com/en-gb/dynamics365/business-central/across-work-with-excel) in a "note" near the bottom of the page says "For Business Central on-premises, the Edit in Excel action is only available if the Excel add-in has been installed by your administrator. For administrators, if you want to learn how to install the excel add-in, see Setting up the Excel Add-In.".  

So which is it?

To further add to the confusion "Setting up the Excel Add-In for Editing Business Central Data" (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin) in the Prerequisites sections says:
"Your deployment must meet the following prerequisites:

Azure Active Directory (Azure AD) used to authenticate users.

The Business Central Server instance, clients, and users must be configured for NavUserPassword, Azure Access Control Service (ACS), or Azure Active Directory (Azure AD) authentication.

For more information, see Authenticating Users with Azure Active Directory."

Note the mention of ACS and NAVUserPassword authentication methods but neither are supported in Saas only in on-premise.
So again which is it.

All these pages state they were all updated on the same date (2019/10/01).

Is there a way to use "Edit in Excel" in an on-premise installation?  

If so what are the steps to set this up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db917c4-601c-b6f1-863f-17b83d35e814
* Version Independent ID: 22279a66-57b2-7f98-16b6-3cfb394b7fda
* Content: [Features not implemented in on-premises deployments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises)
* Content Source: [dev-itpro/features-not-implemented-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/features-not-implemented-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment] 2019-10-24 12:54
Hello @GreatScott000 ,
Thank you for your feedback! We apologize for the confusion that is caused by the product having had 3 very different ways of sending data to Excel that have now been simplified significantly, but unfortunately this is not truly reflected in the documentation. We are in process of consolidating the content across the business functionality content and the developer- and IT Pro content.

You can edit Business Central data in Excel using the same functionality in both Business Central online and Business Central on-premises. For Business Central online, it works automatically, but for Business Central on-premises, you have to configure the Excel add-in. 

The main steps for this is described here, but the detailed steps for working in the Azure portal are not fully up-to-date yet: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin

**Comment by edupont04** [comment] 2019-10-24 15:31
Your second question first: The content in https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin was not verified for version 15 yet. 

As for authentication, again we have not tested this recently, but I believe you should be able to use NavUserPassword as credential type, but the users must be Office 365/Azure AD users: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory

We'll update the docs and this Issue once we have verified this.

**Comment by jswymer** [comment] 2019-10-31 12:20
Hello, the following articles have updated for BC15 on-premises, but it also applies to BC14:

- [Setting up the Excel Add-In for Editing Business Central Data](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin)
- [Authenticating Business Central Users with Azure Active Directory](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory)

Sorry, the original content was incorrect and misleading. NAVUser password authentication is not supported. The environment must be configured to Azure AD authentication as per the guidelines. In short, this means:
- The ClientServicesCredentialType in the configuration files for the Web server (Web client) and Windows client be set to AccessControlService.
- The BC server must be configured with the Azure AD endpoints. The ClientServicesCredentialType can be set to either AccessControlService or NavUserPassword (This might be where the incorrect info originated). The authentication flow from the server point of view is the same for both settings.
- User accounts must be associated with the Azure authentication email.

I hope this help. Thanks for the feedback!

**Comment by GreatScott000** [comment] 2019-10-31 16:02
Thank you for the updates.  I will review then in the next few days

**Comment by jswymer** [comment] 2019-11-29 10:10
Hello, we will close this issue for now. If you find anything more that needs to be looked at, let us know and we will reopen the issue. Thanks!

**Closed by jswymer** 2019-11-29 10:10 UTC
Labels: in-the-plans

**Comment by Nasimkhavari** [comment] 2020-04-15 04:16
hi guys,
as you mentioned, if we have an active directory, not the azure, then we can't use to edit in excel in BC14?
