### ISSUE TITLE
"Report Format" options do not list a valid option, HTML.

### ISSUE THREAD

**Issue by njackson1582** [MicrosoftDocs/dynamics365smb-devitpro-pb#2534] opened 2022-09-02 13:23 UTC
The parameter for `Format` of type `ReportFormat` lists the following valid formats: Pdf, Excel, Word, and XML. However, it does not list another valid format, HTML. The type HTML is listed on the `ReportFormat` option type documentation, but needs to be updated in the `Report.SaveAs` description. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603417a5-e264-835c-6f47-fb1f643e5755
* Version Independent ID: d751df67-69f9-68e8-0ae1-a55ef592939c
* Content: [Report.SaveAs(Integer, Text, ReportFormat, var OutStream \[, RecordRef\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-saveas-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/report/report-saveas-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/report/report-saveas-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment] 2022-09-13 14:32
dupe of https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1389 and thus https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2008 :-)

**Closed** 2022-09-13 14:42 UTC
