### ISSUE TITLE
New rules are missing

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#788] opened 2019-10-17 09:32 UTC
Since BC15 there seems to be a bunch of new rules that are not documented on this page.
I've got these so far:
error AS0032: Control 'xxx' on page 'yyy' has been deleted
error AS0031: Action 'xxx' on page 'yyy' has been deleted.
error AS0029: Page 'xxx' has been deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cc1f40-cea7-5449-10a6-9736f9713c53
* Version Independent ID: afcd6e13-c135-08ba-f973-cab671fb579c
* Content: [AppSourceCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2019-10-21 09:05
Thanks for the feedback. Yes, this is a known issue and we're looking into solving it. This issue is a duplicate of #761 , so I am closing this. Thanks.

**Closed by SusanneWindfeldPedersen** 2019-10-21 09:05 UTC
