### ISSUE TITLE
No useful developer information.

### ISSUE THREAD

**Issue by RealErling** [MicrosoftDocs/dynamics365smb-devitpro-pb#2590] opened 2022-10-24 06:24 UTC
Is it 0 (read zero) or 1 based array. What index is the first element???
That is the information that is needed on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48f5c8ec-fa98-7869-bcb7-7b55feb4aef4
* Version Independent ID: 069473b9-c74f-60f7-a090-ba747f0daf39
* Content: [JsonArray.Get(Integer, var JsonToken) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonarray/jsonarray-get-method)
* Content Source: [dev-itpro/developer/methods-auto/jsonarray/jsonarray-get-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/jsonarray/jsonarray-get-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2022-12-09 11:32
Thanks for the feedback. The array is 0-based, which is by design because these methods are wrappers. Other arrays in AL are 1-based. We will update the docs specifically for the JsonArray data type. Thanks.

**Comment by SusanneWindfeldPedersen** [comment] 2022-12-12 12:49
Closing this issue. Update for the next doc refresh.

**Closed by SusanneWindfeldPedersen** 2022-12-12 12:49 UTC
