### ISSUE TITLE
"Become a contributor" link broken

### ISSUE THREAD

**Issue by eclipses** [MicrosoftDocs/dynamics365smb-devitpro-pb#3089] opened 2023-10-24 16:30 UTC
"Become a contributor" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21e4aa27-1161-d502-7ef5-5a10c8c17839
* Version Independent ID: 8bfa326e-2d20-dcf2-551b-28b5fdd85741
* Content: [Create a New Module in the System Application - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-new-module)
* Content Source: [dev-itpro/developer/devenv-new-module.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-new-module.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by eclipses** [comment] 2023-11-22 19:52
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/3910615/d7941192-8ec1-459c-80d6-3240e9c72565)

**Comment by eclipses** [comment] 2023-11-22 19:53
This is what I see when I click the link

**Comment by SusanneWindfeldPedersen** [comment] 2023-11-24 09:37
Hello, thanks for your feedback. We're not able to reproduce the issue, we checked the links from different locations and machines. Please check if your settings could be blocking the sites somehow. Closing this issue for now. Thanks.

**Closed by SusanneWindfeldPedersen** 2023-11-24 09:37 UTC

**Comment by eclipses** [comment] 2023-11-24 09:46
Hi @SusanneWindfeldPedersen the url has been changes in the page, before had "www" and now it is without. Even @v-nithyamut edited her message to remove the "www". I'm really surprised as rather than say "thank you we fixed the issue" you continue on repeating that you were not able to reproduce. Someone did a change and cannot be denied.
