### ISSUE TITLE
field match

### ISSUE THREAD

**Issue by klauskaan** [MicrosoftDocs/dynamics365smb-devitpro-pb#2043] opened 2021-09-28 05:44 UTC
Could you please elaborate on how fields are matched and what happens with partial matches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66ab2a9-7864-bbdb-7dce-2f8779dfc327
* Version Independent ID: 18950d13-7624-300f-4246-8f4001a1a6cb
* Content: [Record.TransferFields(var Record \[, Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment] 2021-09-28 13:13
duplicate of https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1860

**Comment by SusanneWindfeldPedersen** [comment] 2021-10-01 08:44
Thanks for your patience. The topic wasn't updated correctly and the important Remark went missing. It will be fixed with the next doc refresh. Thanks!

**Closed by SusanneWindfeldPedersen** 2021-10-01 08:44 UTC
Labels: enhancement
