### ISSUE TITLE
I got error Import-NAVData : The specified file does not exist at the specified location: C:\work\navdata\xyz.navdata 

### ISSUE THREAD

**Issue by tokoskel** [MicrosoftDocs/dynamics365smb-devitpro-pb#2118] opened 2021-11-24 23:09 UTC
Import-NAVData : The specified file does not exist at the specified location: C:\work\navdata\xyz.navdata 

When I googled, found out that copying this to c:\ -root resolves this. What is the reason of this behauviour and why you do not tell about this bug?

Link to help:
https://www.myerrorsandmysolutions.com/import-navdata-the-specified-file-does-not-exist-at-the-specified-location/

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c5e762-c88e-7033-90ef-1f2aa61a7d02
* Version Independent ID: 3f96fda0-b938-5c00-47b9-a65adff094a1
* Content: [Import-NAVData (Microsoft.Dynamics.Nav.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/import-navdata?view=businesscentral-ps-19)
* Content Source: [businesscentral-ps-19/Microsoft.Dynamics.Nav.Management/Import-NAVData.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-19/Microsoft.Dynamics.Nav.Management/Import-NAVData.md)
* Product: **dynamics365-business-central**
* GitHub Login: @jswymer

**Comment by jswymer** [comment] 2021-11-25 10:57
Thanks for the valuable feedback! I've added information about the behavior to the article. I've sent a request to the development team for clarification, but it is apparently by design. If I hear back, I will follow up here. For now, I will close the issue. The updated article will be available soon.

**Closed by jswymer** 2021-11-25 10:57 UTC
Labels: powershell
