### ISSUE TITLE
Backslash does not work in Web Client.

### ISSUE THREAD

**Issue by PaulFurlet** [MicrosoftDocs/dynamics365smb-devitpro-pb#977] opened 2020-01-24 18:31 UTC
Will possibility to indicate new line by using backslash be returned to Web Client in foreseen future for all Dialogs (Error, Confirm, Message, Dialog)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49717d03-32ce-96ea-9913-7fd09d4083bd
* Version Independent ID: 3bd0495c-b80a-ba18-c978-f4d1db587f8f
* Content: [Confirm Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-confirm-method)
* Content Source: [dev-itpro/developer/methods-auto/dialog/dialog-confirm-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/dialog/dialog-confirm-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2020-02-05 10:25
Hello, this sounds like a regression - which version are you on? Thanks.

**Comment by PaulFurlet** [comment] 2020-02-05 13:04
> Hello, this sounds like a regression - which version are you on? Thanks.

any version of Business Central, Web Client.

**Comment by SusanneWindfeldPedersen** [comment] 2020-02-05 13:53
I cannot reproduce. If I run this code on the Web client version 15.x:

pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Message('App published: Hello world');

        CustomerNo := 01121212;
        Question := Text000;
        Answer := Dialog.CONFIRM(Question, TRUE, CustomerNo);
        MESSAGE(Text001, Answer);

    end;

    var
        Question: Text;
        Answer: Boolean;
        CustomerNo: Integer;
        Text000: Label 'Exit without saving changes to customer \%1?';
        Text001: Label 'You selected %1.';
}

Then I get a dialog where the text "Exit without saving changes to customer" is on one line and
"1121212?" is on a new line.

**Comment by PaulFurlet** [comment] 2020-02-05 15:11
Got a clue!
I guess you are checking in cloud?
I just reensured docker and on-prem have this issue.

**Comment by SusanneWindfeldPedersen** [comment] 2020-02-06 08:01
Hello again - I tested this on an on-prem (no Docker install) and had no issues. It sounds like a bug. Please open a product bug with information about which environment you're using. Thanks.

**Comment by SusanneWindfeldPedersen** [comment] 2020-02-07 08:55
Closing this issue for now. Thanks.

**Closed by SusanneWindfeldPedersen** 2020-02-07 08:55 UTC
Labels: product
