### ISSUE TITLE
Link to files

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1691] opened 2021-02-05 09:07 UTC
> When using the file:// protocol to open a file, the file should be stored on a network file share, not locally; otherwise the file will not open. Also, certain browsers, including Google Chrome, Mozilla Firefox, block hyperlinks to files from a web page. Therefore, using the files:// protocol in the HyperLink function will not work with these browsers.

Can you verify that the section still valid?
I tried Edge and Internet Explorer, and both do not support opening a file link neither. 
With all my tested browsers, I'd need to manually open a new browser tab and paste the URL. That would open/download the file.

Also, I've tested it with a locally stored text file - it worked as well, in Google Chrome at least, in a manually opened tab.

Is there maybe a chance to open/download a file just by clicking on the link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7543dd1-8323-2341-7eb9-d2cc9fa81083
* Version Independent ID: 04e0fad0-745e-7434-4ec8-8a1df588a098
* Content: [System.Hyperlink Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-hyperlink-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-hyperlink-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-hyperlink-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment] 2021-02-08 13:22
Hello, thanks for your feedback. I agree, I don't think this is working as intended. Can you please file a product bug on this? Thanks

**Comment by NKarolak** [comment] 2021-02-08 14:23
Hi Susanne,

it looks like a docs issue.
I've talked quickly to Duilio Tacconi about it, and he confirmed my suspicion, by sharing:
https://community.dynamics.com/business/f/dynamics-365-business-central-forum/397518/web-client-and-record-links

**Comment by SusanneWindfeldPedersen** [comment] 2021-02-09 08:59
Hi Natalie, thanks for this - we'll look further into it and get the docs updated. Thanks!

**Comment by SusanneWindfeldPedersen** [comment] 2021-02-15 09:54
Thanks for catching this. The issue will be fixed with the next doc refresh.

**Closed by SusanneWindfeldPedersen** 2021-02-15 09:54 UTC
Labels: bug
